apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
  name: grafana
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30292
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
